partition: a100
gres: gpu:1
cpus_per_task: 16
mem_gb: 32
nodes: 1
tasks_per_node: 1
timeout_min: 2880
name: ${hydra.job.name}
signal_delay_s: 120
max_num_timeout: 0
additional_parameters:
  mail-type: ALL
  mail-user: xxxxxxxx@gmail.com
